--1
SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE YEAR<2000 AND (LENGTH>120 OR LENGTH IS NULL);

--2
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE BIRTHDATE>1948 AND NAME LIKE 'J%'
ORDER BY NAME DESC;

--3
SELECT STUDIONAME, COUNT(DISTINCT STARNAME) AS NUM_ACTORS
FROM MOVIE
	JOIN STARSIN ON MOVIE.TITLE=STARSIN.MOVIETITLE
GROUP BY STUDIONAME;

--4
SELECT STARNAME, COUNT(*) AS NUM_MOVIES
FROM STARSIN
GROUP BY STARNAME;

--5
SELECT STUDIONAME, TITLE, YEAR
FROM MOVIE M
WHERE YEAR=(SELECT MAX(YEAR) FROM MOVIE WHERE M.STUDIONAME=STUDIONAME);

--6
SELECT NAME
FROM MOVIESTAR
WHERE BIRTHDATE=(SELECT MAX(BIRTHDATE) FROM MOVIESTAR WHERE GENDER='M');

--7
SELECT STUDIONAME, STARNAME, COUNT(*) AS NUM_MOVIES
FROM MOVIE
	JOIN STARSIN ON MOVIETITLE=TITLE
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(*)=(SELECT TOP 1 COUNT(*) FROM MOVIE JOIN STARSIN ON MOVIETITLE=TITLE GROUP BY STARNAME ORDER BY COUNT(*) DESC);

SELECT STUDIONAME, STARNAME, COUNT(*) AS NUM_MOVIES
FROM MOVIE M1
	RIGHT JOIN STARSIN S1 ON MOVIETITLE=TITLE AND YEAR=MOVIEYEAR
GROUP BY STUDIONAME, STARNAME
HAVING COUNT(*)>=ALL(SELECT COUNT(*) FROM MOVIE JOIN STARSIN ON TITLE=MOVIETITLE AND M1.STUDIONAME=STUDIONAME GROUP BY STUDIONAME, STARNAME);

--8
SELECT MOVIETITLE, MOVIEYEAR, COUNT(*) AS NUM_ACTORS
FROM STARSIN
GROUP BY MOVIETITLE,MOVIEYEAR
HAVING COUNT(*)>2;