--1
SELECT MODEL,CODE,SCREEN
FROM LAPTOP
WHERE (SCREEN=11 AND MODEL IN (SELECT MODEL
							FROM LAPTOP
							WHERE SCREEN=15))
	OR (SCREEN=15 AND MODEL IN (SELECT MODEL
							FROM LAPTOP
							WHERE SCREEN=11));

SELECT MODEL,CODE,SCREEN
FROM LAPTOP
WHERE (SCREEN=11 OR SCREEN=15)
	AND MODEL IN (SELECT MODEL
				FROM LAPTOP
				WHERE SCREEN=11 OR SCREEN=15
				GROUP BY MODEL HAVING COUNT(MODEL)>1);

--2
SELECT DISTINCT PC.MODEL
FROM PC
	JOIN PRODUCT PR ON PR.MODEL=PC.MODEL
WHERE PRICE<(SELECT MIN(PRICE)
			FROM LAPTOP
				JOIN PRODUCT ON LAPTOP.MODEL=PRODUCT.MODEL
			WHERE PR.MAKER=PRODUCT.MAKER);

--3
SELECT PC.MODEL, AVG(PRICE) AVG_PRICE
FROM PC
	JOIN PRODUCT PR ON PC.MODEL=PR.MODEL
GROUP BY PC.MODEL,PR.MAKER
HAVING AVG(PRICE)<(SELECT MIN(PRICE)
				FROM LAPTOP
					JOIN PRODUCT ON LAPTOP.MODEL=PRODUCT.MODEL
				WHERE PR.MAKER=PRODUCT.MAKER);

--4
SELECT P1.CODE, MAKER, COUNT(*) AS NUM_PC_HIGHER_PRICE
FROM PC P1
	JOIN PRODUCT PR ON P1.MODEL=PR.MODEL
	JOIN PC P2 ON P2.PRICE>=P1.PRICE AND P1.MODEL=P2.MODEL
GROUP BY P1.CODE,MAKER;