--1
SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE (SHIP LIKE 'C%' OR SHIP LIKE 'K%') AND BATTLE IS NOT NULL;

--2
SELECT NAME, COUNTRY
FROM CLASSES
	JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
WHERE NAME NOT IN (SELECT SHIP
				FROM OUTCOMES
				WHERE RESULT='sunk');

--3
SELECT COUNTRY, COUNT(NAME) AS NUM_SUNK_SHIPS
FROM CLASSES C
	LEFT JOIN (SELECT NAME,CLASS
			FROM SHIPS JOIN OUTCOMES ON SHIP=NAME
			WHERE RESULT='sunk') S ON C.CLASS=S.CLASS
GROUP BY COUNTRY;

SELECT COUNTRY, COUNT(NAME) AS NUM_SUNK_SHIPS
FROM SHIPS S
	JOIN OUTCOMES ON SHIP=NAME
	RIGHT JOIN CLASSES C ON S.CLASS=C.CLASS
WHERE RESULT='sunk' OR S.CLASS IS NULL OR RESULT IS NULL
GROUP BY COUNTRY;

--4
SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(SHIP)>(SELECT COUNT(SHIP)
					FROM OUTCOMES
					WHERE BATTLE='Guadalcanal');

--5
SELECT BATTLE
FROM OUTCOMES O
	JOIN SHIPS S ON SHIP=NAME
	JOIN CLASSES C ON C.CLASS=S.CLASS
GROUP BY BATTLE
HAVING COUNT(COUNTRY) > (SELECT COUNT(COUNTRY)
						FROM OUTCOMES
							JOIN SHIPS S1 ON SHIP=NAME
							JOIN CLASSES C1 ON C1.CLASS=S1.CLASS
						WHERE BATTLE='Surigao Strait');

--6
SELECT NAME, DISPLACEMENT, NUMGUNS
FROM CLASSES C
	JOIN SHIPS S ON C.CLASS=S.CLASS
WHERE NUMGUNS=(SELECT MAX(NUMGUNS) FROM CLASSES WHERE DISPLACEMENT=(SELECT MIN(DISPLACEMENT) FROM CLASSES)) 
	AND DISPLACEMENT=(SELECT MIN(DISPLACEMENT) FROM CLASSES);

--7
SELECT COUNT(SHIP) AS NUM_SHIPS
FROM OUTCOMES O 
	JOIN BATTLES B ON BATTLE=NAME
WHERE RESULT='damaged'
	AND SHIP IN (SELECT SHIP FROM OUTCOMES JOIN BATTLES ON BATTLE=NAME WHERE B.DATE<DATE AND RESULT='ok');

--8
SELECT SHIP
FROM OUTCOMES O, BATTLES B
WHERE RESULT='damaged' AND O.BATTLE=B.NAME
GROUP BY SHIP,DATE
HAVING COUNT(SHIP)<ANY(SELECT COUNT(SHIP)
						FROM OUTCOMES,BATTLES
						WHERE RESULT='ok' AND SHIP=O.SHIP AND			B.DATE<DATE)