--1
SELECT AVG(SPEED) AS AVG_SPEED
FROM PC;

--2
SELECT MAKER, AVG(SCREEN) AS AVG_SCREEN
FROM PRODUCT P
	JOIN LAPTOP L ON P.MODEL=L.MODEL
GROUP BY MAKER;

--3
SELECT AVG(SPEED) AS AVG_SPEED
FROM LAPTOP
WHERE PRICE>1000;

--4
SELECT MAKER, AVG(PRICE) AS AVG_PRICE
FROM PRODUCT PR
	JOIN PC P ON PR.MODEL=P.MODEL
GROUP BY MAKER
HAVING MAKER='A';

--5
SELECT MAKER, AVG(PRICE) AS AVG_PRICE
FROM PRODUCT PR
	JOIN (SELECT PRICE,MODEL FROM PC UNION ALL
		SELECT PRICE,MODEL FROM LAPTOP) PL ON PR.MODEL=PL.MODEL
GROUP BY MAKER
HAVING MAKER='B';

--6
SELECT SPEED, AVG(PRICE) AS AVG_PRICE
FROM PC
GROUP BY SPEED;

--7
SELECT MAKER, COUNT(DISTINCT CODE) AS NUMBER_OF_PC
FROM PRODUCT
	JOIN PC ON PRODUCT.MODEL=PC.MODEL
GROUP BY MAKER
HAVING COUNT(DISTINCT CODE)>=3;

--8
SELECT MAKER, PRICE
FROM PRODUCT
	JOIN PC ON PC.MODEL=PRODUCT.MODEL
WHERE PRICE=(SELECT MAX(PRICE) FROM PC);

--9
SELECT SPEED, AVG(PRICE) AS AVG_PRICE
FROM PC
GROUP BY SPEED
HAVING SPEED>800;

--10
SELECT MAKER, AVG(HD) AS AVG_HD
FROM PRODUCT
	JOIN PC ON PC.MODEL=PRODUCT.MODEL
WHERE MAKER IN (SELECT MAKER FROM PRODUCT WHERE TYPE='Printer')
GROUP BY MAKER;