--1
SELECT COUNT(CLASS) AS NUM_CLASSES
FROM CLASSES
WHERE TYPE='bb';

--2
SELECT CLASS, AVG(NUMGUNS) AS AVG_GUNS
FROM CLASSES
WHERE TYPE='bb'
GROUP BY CLASS;

--3
SELECT AVG(NUMGUNS) AS AVG_GUNS
FROM CLASSES
WHERE TYPE='bb';

--4
SELECT CLASS, MIN(LAUNCHED) AS FIRSTYEAR, MAX(LAUNCHED) AS LASTYEAR
FROM SHIPS
GROUP BY CLASS;

--5
SELECT CLASS, COUNT(RESULT) AS NUM_SUNK
FROM SHIPS
	JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE RESULT='sunk'
GROUP BY CLASS;

--6
SELECT CLASS, COUNT(RESULT) AS NUM_SUNK
FROM SHIPS S
	JOIN OUTCOMES ON S.NAME=OUTCOMES.SHIP
WHERE RESULT='sunk'
GROUP BY CLASS
HAVING (SELECT COUNT(CLASS) FROM SHIPS WHERE CLASS=S.CLASS)>2;

--7 
SELECT COUNTRY, AVG(BORE) AS AVG_BORE
FROM CLASSES C
	JOIN SHIPS S ON S.CLASS=C.CLASS
GROUP BY COUNTRY;