USE ships
GO

--8
IF EXISTS (SELECT NAME FROM sys.views WHERE NAME='V_BATTLES_GT_GUADALCANAL_SHIPS')
	DROP VIEW V_BATTLES_GT_GUADALCANAL_SHIPS
GO
CREATE VIEW V_BATTLES_GT_GUADALCANAL_SHIPS
AS
	SELECT DISTINCT BATTLE
	FROM OUTCOMES O
	WHERE (SELECT COUNT(DISTINCT SHIP)
		FROM OUTCOMES
		WHERE BATTLE=O.BATTLE)>(SELECT COUNT(DISTINCT SHIP)
					FROM OUTCOMES
					WHERE BATTLE='Guadalcanal')
GO

SELECT * FROM V_BATTLES_GT_GUADALCANAL_SHIPS;
GO

IF EXISTS (SELECT NAME FROM sys.views WHERE NAME='V_BATTLES_GT_GUADALCANAL_COUNTRY')
	DROP VIEW V_BATTLES_GT_GUADALCANAL_COUNTRY
GO
CREATE VIEW V_BATTLES_GT_GUADALCANAL_COUNTRY
AS
	SELECT DISTINCT BATTLE
	FROM OUTCOMES O
	WHERE (SELECT COUNT(DISTINCT COUNTRY)
		FROM OUTCOMES
			JOIN SHIPS S ON S.NAME=SHIP
			JOIN CLASSES C ON C.CLASS=S.CLASS
		WHERE BATTLE=O.BATTLE)>(SELECT COUNT(DISTINCT COUNTRY)
					FROM OUTCOMES
						JOIN SHIPS S ON S.NAME=SHIP
						JOIN CLASSES C ON C.CLASS=S.CLASS
					WHERE BATTLE='Guadalcanal')
GO

SELECT * FROM V_BATTLES_GT_GUADALCANAL_COUNTRY;
GO

--9
DELETE FROM OUTCOMES
WHERE BATTLE IN (SELECT COUNT(DISTINCT SHIP)
				FROM OUTCOMES
				GROUP BY BATTLE
				HAVING COUNT(DISTINCT SHIP)=1);

--10
INSERT INTO outcomes VALUES
('Missouri','Surigao Strait', 'sunk'),
('Missouri','North Cape', 'sunk'),
('Missouri','North Atlantic', 'ok');
DELETE FROM OUTCOMES
WHERE RESULT LIKE 'sunk' AND SHIP IN (SELECT SHIP
									FROM OUTCOMES O
									WHERE (SELECT COUNT(*)
										FROM OUTCOMES
										WHERE O.SHIP=SHIP AND RESULT LIKE 'SUNK')>=2);

SELECT * FROM OUTCOMES ORDER BY SHIP;
GO

--11
IF EXISTS (SELECT NAME FROM sys.views WHERE NAME='V_BATTLES_COUNTRIES')
	DROP VIEW V_BATTLES_COUNTRIES
GO
CREATE VIEW V_BATTLES_COUNTRIES
AS
	SELECT DISTINCT BATTLE, COUNTRY
	FROM OUTCOMES
		JOIN SHIPS ON SHIP=NAME
		JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
GO

SELECT * FROM V_BATTLES_COUNTRIES;
GO

SELECT V.BATTLE
FROM V_BATTLES_COUNTRIES V
	JOIN (SELECT *
		FROM V_BATTLES_COUNTRIES
		WHERE BATTLE LIKE 'Guadalcanal') G ON V.COUNTRY=G.COUNTRY
WHERE V.BATTLE NOT LIKE 'Guadalcanal'
GROUP BY V.BATTLE
HAVING COUNT(*)=(SELECT COUNT(*)
					FROM V_BATTLES_COUNTRIES
					WHERE BATTLE LIKE 'Guadalcanal');

--12
SELECT COUNTRY, COUNT(BATTLE) AS NUM_BATTLES
FROM (SELECT DISTINCT COUNTRY,BATTLE
	FROM CLASSES
		LEFT JOIN SHIPS S ON CLASSES.CLASS=S.CLASS
		LEFT JOIN OUTCOMES O ON O.SHIP=S.NAME) S
GROUP BY COUNTRY;