USE master
GO
IF EXISTS (SELECT * FROM sysdatabases WHERE NAME='Flights')
	DROP DATABASE Flights
GO

CREATE DATABASE Flights
GO
USE Flights
GO

-- Tables

CREATE TABLE AIRLINE(
	CODE VARCHAR(10) NOT NULL CONSTRAINT PK_AIRLINE PRIMARY KEY(CODE),
	NAME VARCHAR(50) NOT NULL CONSTRAINT UK_AIRLINE UNIQUE(NAME),
	COUNTRY VARCHAR(20) NOT NULL,
);

CREATE TABLE AIRPLANE(
	CODE VARCHAR(10) NOT NULL CONSTRAINT PK_AIRPLANE PRIMARY KEY(CODE),
	TYPE VARCHAR(50) NOT NULL,
	SEATS INT NOT NULL CHECK(SEATS>0),
	YEAR INT NOT NULL,
);

CREATE TABLE AIRPORT(
	CODE VARCHAR(10) NOT NULL CONSTRAINT PK_AIRPORT PRIMARY KEY(CODE),
	NAME VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(20) NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	CONSTRAINT UK_AIRPORT UNIQUE(NAME,COUNTRY)
);

CREATE TABLE FLIGHT(
	FNUMBER VARCHAR(10) NOT NULL CONSTRAINT PK_FLIGHT PRIMARY KEY(FNUMBER),
	AIRLINE_OPERATOR VARCHAR(10) CONSTRAINT FK_AIRLINE REFERENCES AIRLINE(CODE) ON UPDATE CASCADE ON DELETE SET NULL,
	DEP_AIRPORT VARCHAR(10) NOT NULL CONSTRAINT FK_AIRPORT_FLIGHT_DEP REFERENCES AIRPORT(CODE),
	ARR_AIRPORT VARCHAR(10) NOT NULL CONSTRAINT FK_AIRPORT_FLIGHT_ARR REFERENCES AIRPORT(CODE),
	FLIGHT_TIME CHAR(5),
	FLIGHT_DURATION INT,
	AIRPLANE VARCHAR(10) CONSTRAINT FK_AIRPORT2 REFERENCES AIRPLANE(CODE) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT CH_FLIGHT CHECK(FLIGHT_TIME LIKE '%:%')
);

CREATE TABLE CUSTOMER(
	ID INT NOT NULL CONSTRAINT PK_CUSTOMER PRIMARY KEY(ID),
	FNAME VARCHAR(20),
	LNAME VARCHAR(20),
	EMAIL VARCHAR(50),
	CONSTRAINT CH_CUSTOMER CHECK(EMAIL LIKE '%@%.%' AND LEN(EMAIL)>=6)
);

CREATE TABLE AGENCY(
	NAME VARCHAR(50) NOT NULL CONSTRAINT PK_AGENCY PRIMARY KEY(NAME),
	COUNTRY VARCHAR(20),
	CITY VARCHAR(20),
	PHONE VARCHAR(10),
	
);

CREATE TABLE BOOKING(
	CODE VARCHAR(10) NOT NULL,
	AGENCY VARCHAR(50) NOT NULL CONSTRAINT FK_AGENCY_BOOKING REFERENCES AGENCY(NAME) ON UPDATE CASCADE ON DELETE NO ACTION,
	AIRLINE_CODE VARCHAR(10) NOT NULL CONSTRAINT FK_AIRLINE_BOOKING REFERENCES AIRLINE(CODE) ON UPDATE CASCADE ON DELETE NO ACTION,
	FLIGHT_NUMBER VARCHAR(10) NOT NULL CONSTRAINT FK_FLIGHT_BOOKING REFERENCES FLIGHT(FNUMBER) ON UPDATE CASCADE ON DELETE NO ACTION,
	CUSTOMER_ID INT NOT NULL CONSTRAINT FK_CUSTOMER REFERENCES CUSTOMER(ID) ON UPDATE CASCADE ON DELETE NO ACTION,
	BOOKING_DATE DATE NOT NULL,
	FLIGHT_DATE DATE NOT NULL,
	PRICE DECIMAL(16,2) NOT NULL,
	STATUS INT NOT NULL,
	CONSTRAINT PK_BOOKING PRIMARY KEY(CODE),
	CONSTRAINT CH_BOOKING CHECK(FLIGHT_DATE>=BOOKING_DATE AND STATUS IN(0,1))
);

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS;

SELECT * FROM AGENCY