--1
SELECT NAME
FROM MOVIESTAR
WHERE GENDER='M'
INTERSECT
SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE='The Usual Suspects';

--2
SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR=1995
UNION
SELECT NAME
FROM MOVIEEXEC
WHERE NAME='MGM';

--3
SELECT DISTINCT NAME 
FROM MOVIE,MOVIEEXEC 
WHERE STUDIONAME='MGM' AND PRODUCERC#=CERT#;

--4
SELECT M1.TITLE 
FROM MOVIE AS M1, MOVIE AS M2 
WHERE M2.TITLE='Star Wars' AND M1.LENGTH>M2.LENGTH;

--5
SELECT M1.NAME 
FROM MOVIEEXEC M1, MOVIEEXEC AS M2 
WHERE M2.NAME='Stephen Spielberg' AND M1.NETWORTH>M2.NETWORTH;

--6
SELECT MOVIE.TITLE
FROM MOVIE, MOVIEEXEC AS ME1, MOVIEEXEC AS ME2
WHERE ME2.NAME='Stephen Spielberg' AND ME1.NETWORTH>ME2.NETWORTH AND PRODUCERC#=ME1.CERT#;