--1
SELECT MAKER, SPEED 
FROM LAPTOP, PRODUCT 
WHERE HD>=9 AND LAPTOP.MODEL=PRODUCT.MODEL;

--2
SELECT PRINTER.MODEL, PRICE
FROM PRINTER, PRODUCT
WHERE PRODUCT.MAKER='B' AND PRINTER.MODEL=PRODUCT.MODEL
UNION
SELECT PC.MODEL, PRICE
FROM PC, PRODUCT
WHERE PRODUCT.MAKER='B' AND PC.MODEL=PRODUCT.MODEL
UNION
SELECT LAPTOP.MODEL, PRICE
FROM LAPTOP, PRODUCT
WHERE PRODUCT.MAKER='B' AND LAPTOP.MODEL=PRODUCT.MODEL;

--3
SELECT MAKER
FROM PRODUCT, LAPTOP
WHERE PRODUCT.MODEL=LAPTOP.MODEL
EXCEPT
SELECT MAKER
FROM PRODUCT, PC
WHERE PRODUCT.MODEL=PC.MODEL;

--4
SELECT DISTINCT PC1.HD
FROM PC AS PC1, PC AS PC2
WHERE PC1.CODE<>PC2.CODE AND PC1.HD=PC2.HD;

--5
SELECT DISTINCT PC1.MODEL, PC2.MODEL
FROM PC AS PC1, PC AS PC2
WHERE PC1.SPEED=PC2.SPEED AND PC1.RAM=PC2.RAM AND PC1.MODEL<PC2.MODEL;

--6
SELECT DISTINCT P1.MAKER
FROM PRODUCT AS P1, PRODUCT AS P2, PC AS PC1, PC AS PC2
WHERE PC1.SPEED>=400 AND PC2.SPEED>=400 AND PC1.CODE<>PC2.CODE AND PC1.MODEL=P1.MODEL AND PC2.MODEL=P2.MODEL AND P1.MAKER=P2.MAKER;