--1
SELECT NAME
FROM SHIPS, CLASSES
WHERE DISPLACEMENT>50000 AND CLASSES.CLASS=SHIPS.CLASS;

--2
SELECT NAME, DISPLACEMENT, NUMGUNS
FROM SHIPS, CLASSES, OUTCOMES
WHERE NAME=OUTCOMES.SHIP AND OUTCOMES.BATTLE='Guadalcanal' AND SHIPS.CLASS=CLASSES.CLASS;

--3
SELECT C1.COUNTRY
FROM CLASSES AS C1, CLASSES AS C2
WHERE C1.TYPE='bb' AND C2.TYPE='bc' AND C1.COUNTRY=C2.COUNTRY;

--4
SELECT O1.SHIP
FROM OUTCOMES AS O1, OUTCOMES AS O2, BATTLES AS B1, BATTLES AS B2
WHERE O1.SHIP=O2.SHIP AND O1.RESULT='damaged' AND O2.RESULT='ok' AND O1.BATTLE=B1.NAME AND O2.BATTLE=B2.NAME AND B1.DATE<B2.DATE;