--1
SELECT MAKER
FROM PRODUCT
WHERE MODEL IN(SELECT MODEL FROM PC WHERE SPEED>500);

--2
SELECT CODE, MODEL, PRICE
FROM PRINTER
WHERE PRICE>=ALL(SELECT PRICE FROM PRINTER);

--3
SELECT *
FROM LAPTOP
WHERE SPEED<ALL(SELECT SPEED FROM PC);

--4
SELECT MODEL, PRICE
FROM (SELECT MODEL, PRICE FROM PC UNION
	SELECT MODEL, PRICE FROM LAPTOP UNION
	SELECT MODEL, PRICE FROM PRINTER) PR
WHERE PRICE>=ALL(SELECT PRICE FROM PC UNION
				SELECT PRICE FROM LAPTOP UNION
				SELECT PRICE FROM PRINTER);

--5
--SELECT prod.MAKER
--FROM PRODUCT prod, (SELECT * FROM PRINTER WHERE COLOR='y') prin
--WHERE prod.MODEL=prin.MODEL AND prin.PRICE<=ALL(SELECT PRICE FROM PRINTER WHERE COLOR='y');

SELECT MAKER
FROM PRODUCT
WHERE MODEL IN(SELECT MODEL FROM PRINTER WHERE COLOR='y' AND PRICE<=ALL(SELECT PRICE FROM PRINTER WHERE COLOR='y'));

--6
--SELECT MAKER
--FROM PRODUCT pr, (SELECT * FROM PC WHERE RAM<=ALL(SELECT RAM FROM PC)) pc
--WHERE pr.MODEL=pc.MODEL AND pc.SPEED>=ALL(SELECT SPEED FROM PC WHERE RAM<=ALL(SELECT RAM FROM PC));

SELECT DISTINCT MAKER
FROM PRODUCT
WHERE MODEL IN(SELECT MODEL FROM PC WHERE RAM<ALL(SELECT RAM FROM PC WHERE SPEED>=ALL(SELECT SPEED FROM PC)));