USE pc;

--4
INSERT INTO PRODUCT
VALUES('C','1100','PC');

INSERT INTO PC
VALUES(12,'1100',2400,2048,500,'52x',299);

--5
DELETE FROM PC
WHERE MODEL='1100';

--6
DELETE FROM LAPTOP
WHERE MODEL IN (SELECT MODEL
				FROM PRODUCT
				WHERE TYPE='Laptop' AND MAKER NOT IN (SELECT MAKER
													FROM PRODUCT
													WHERE TYPE='Printer'));

--7
UPDATE PRODUCT
SET MAKER='A'
WHERE MAKER='B';

--8
UPDATE PC
SET PRICE/=2,
	HD+=20;

--9
UPDATE LAPTOP
SET SCREEN+=1
WHERE MODEL IN (SELECT MODEL
				FROM PRODUCT
				WHERE MAKER='B' AND TYPE='Laptop');

USE master;