USE ships;

--10
INSERT INTO CLASSES
VALUES('Nelson','bb','Gt.Britain',9,16,34000);

INSERT INTO SHIPS
VALUES('Nelson','Nelson',1927);

INSERT INTO SHIPS
VALUES('Rodney','Nelson',1927);

--11
DELETE FROM SHIPS
WHERE NAME IN (SELECT SHIP
				FROM OUTCOMES
				WHERE RESULT='sunk');

--12
UPDATE CLASSES
SET BORE*=2.5,
	DISPLACEMENT*=1/1.1;

USE master;