--8
CREATE CLUSTERED INDEX idx_product_m ON product(model)
GO

--9
CREATE CLUSTERED INDEX IDX_UBATTLES ON BATTLES(NAME)
CREATE CLUSTERED INDEX IDX_UCLASSES ON CLASSES(CLASS)
CREATE CLUSTERED INDEX IDX_UOUTCOMES ON OUTCOMES(SHIP,BATTLE)
CREATE CLUSTERED INDEX IDX_USHIPS ON SHIPS(NAME)
GO
	
--10
DROP INDEX idx_product_m ON product;
DROP INDEX IDX_UCLASSES,IDX_UBATTLES,IDX_UOUTCOMES,IDX_USHIPS ON SHIPS;