--1
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME='V_FLIGHT_CUSTOMERS')
	DROP VIEW V_FLIGHT_CUSTOMERS
GO

CREATE VIEW V_FLIGHT_CUSTOMERS (AIRLINE_CODE, FLIGHT_NUMBER, CUSTOMERS_COUNT)
AS
	SELECT AIRLINES.NAME,FLIGHT_NUMBER,COUNT(*)
	FROM BOOKINGS
		JOIN AIRLINES ON AIRLINE_CODE=AIRLINES.CODE
	WHERE STATUS=1
	GROUP BY AIRLINES.NAME,FLIGHT_NUMBER
GO

SELECT * FROM V_FLIGHT_CUSTOMERS
GO

--2
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME='V_AGENCY_CUST_RESERV')
	DROP VIEW V_AGENCY_CUST_RESERV
GO

CREATE VIEW V_AGENCY_CUST_RESERV (AGENCY,NAME,SURNAME)
AS
	SELECT NAME,FNAME,LNAME
	FROM AGENCIES,CUSTOMERS
	WHERE ID=(SELECT TOP 1 CUSTOMER_ID
			FROM BOOKINGS
			WHERE AGENCY=AGENCIES.NAME
			GROUP BY CUSTOMER_ID
			ORDER BY COUNT(*) DESC)
GO

SELECT * FROM V_AGENCY_CUST_RESERV
GO

--3
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME='V_AGENCIES_SOFIA')
	DROP VIEW V_AGENCIES_SOFIA
GO

CREATE VIEW V_AGENCIES_SOFIA
AS
	SELECT *
	FROM AGENCIES
	WHERE CITY='SOFIA'
WITH CHECK OPTION
GO

--INSERT INTO V_AGENCIES_SOFIA VALUES('Travel 100', 'Bulgaria', 'Turnovo', '0783482233')
--GO
SELECT * FROM V_AGENCIES_SOFIA
GO

--4
IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME='V_AGENCIES_NOPHONE')
	DROP VIEW V_AGENCIES_NOPHONE
GO

CREATE VIEW V_AGENCIES_NOPHONE
AS
	SELECT *
	FROM AGENCIES
	WHERE PHONE IS NULL
WITH CHECK OPTION
GO

--INSERT INTO V_AGENCIES_NOPHONE VALUES('Travel 100', 'Bulgaria', 'Turnovo','049324382')
--GO
SELECT * FROM V_AGENCIES_NOPHONE
GO

--5
INSERT INTO V_AGENCIES_SOFIA 
VALUES('T1 Tour', 'Bulgaria', 'Sofia','+359');
INSERT INTO V_AGENCIES_NOPHONE 
VALUES('T2 Tour', 'Bulgaria', 'Sofia',null);
INSERT INTO V_AGENCIES_SOFIA 
VALUES('T3 Tour', 'Bulgaria', 'Varna','+359');
INSERT INTO V_AGENCIES_NOPHONE 
VALUES('T4 Tour', 'Bulgaria', 'Varna',null);
INSERT INTO V_AGENCIES_NOPHONE 
VALUES('T4 Tour', 'Bulgaria', 'Sofia','+359');
GO

--6
--Първите две не могат, защото са декларирани върху повече от една таблица
--Последните две са прости и са updateable

--7
WHILE EXISTS (SELECT TOP 1 NAME FROM SYS.VIEWS)
BEGIN
	DECLARE @query VARCHAR(MAX) = 'DROP VIEW ' + QUOTENAME((SELECT TOP 1 TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS))
	EXEC(@query)
END