
--1
SELECT TITLE, NAME
FROM MOVIEEXEC M1 
	JOIN MOVIE M2 ON CERT#=PRODUCERC#
WHERE CERT#=(SELECT PRODUCERC# FROM MOVIE WHERE TITLE='Star Wars');

--2
SELECT DISTINCT NAME
FROM MOVIEEXEC ME
	JOIN MOVIE M ON ME.CERT#=M.PRODUCERC#
	JOIN STARSIN S ON M.TITLE=S.MOVIETITLE
WHERE S.STARNAME='Harrison Ford';

--3
SELECT DISTINCT NAME, STARNAME
FROM STUDIO S
	JOIN MOVIE M ON S.NAME=M.STUDIONAME
	JOIN STARSIN SI ON SI.MOVIETITLE=M.TITLE
ORDER BY NAME;

--4
SELECT STARNAME, NETWORTH, TITLE
FROM STARSIN SI
	JOIN MOVIE M ON M.TITLE=SI.MOVIETITLE
	JOIN MOVIEEXEC ME ON ME.CERT#=M.PRODUCERC#
WHERE ME.NETWORTH>=ALL(SELECT NETWORTH FROM MOVIEEXEC);

--5
SELECT NAME, MOVIETITLE
FROM MOVIESTAR LEFT
	JOIN STARSIN ON NAME=STARNAME
WHERE MOVIETITLE IS NULL;