--1
SELECT PROD.MAKER,PROD.MODEL,PROD.TYPE
FROM PRODUCT PROD
	LEFT JOIN PC P ON P.MODEL=PROD.MODEL
	LEFT JOIN PRINTER PR ON PR.MODEL=PROD.MODEL
	LEFT JOIN LAPTOP L ON L.MODEL=PROD.MODEL
WHERE L.MODEL IS NULL AND PR.MODEL IS NULL AND P.MODEL IS NULL;

--2
--SELECT MAKER
--FROM PRODUCT L
--	JOIN LAPTOP R ON L.MODEL=R.MODEL
--INTERSECT
--SELECT MAKER
--FROM PRODUCT L
--	JOIN PRINTER R ON L.MODEL=R.MODEL;

SELECT DISTINCT P1.MAKER
FROM PRODUCT P1
	JOIN PRODUCT P2 ON P1.MAKER = P2.MAKER
WHERE P1.TYPE='Laptop' AND P2.TYPE='Printer';

--3
SELECT DISTINCT L.HD
FROM LAPTOP L
	JOIN LAPTOP R ON L.HD=R.HD
WHERE L.CODE<>R.CODE;

--4
--SELECT L.MODEL
--FROM PC L
--	LEFT JOIN PRODUCT R	ON L.MODEL=R.MODEL
--EXCEPT
--SELECT L.MODEL
--FROM PC L 
--	RIGHT JOIN PRODUCT R ON L.MODEL=R.MODEL;

SELECT P.MODEL
FROM PC P
	LEFT JOIN PRODUCT PR ON P.MODEL=PR.MODEL
WHERE PR.MAKER IS NULL;